Resources:
  CloudFrontDistributionMovies:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CacheBehaviors:
          - AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            ForwardedValues:
              Cookies:
                Forward: none
              Headers:
                - Accept
                - Access-Control-Request-Headers
                - Access-Control-Request-Method
                - Origin
              QueryString: true
              QueryStringCacheKeys:
                - d
            LambdaFunctionAssociations:
              - EventType: viewer-request
                LambdaFunctionARN: ForwardImageRequestLambdaFunction
              - EventType: origin-response
                LambdaFunctionARN: ResizeImageLambdaFunction
            MinTTL: 100
            PathPattern: '*.jpg'
            TargetOriginId:
              Ref: S3BucketMovies
            ViewerProtocolPolicy: redirect-to-https
          - AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            ForwardedValues:
              Cookies:
                Forward: none
              Headers:
                - Accept
                - Access-Control-Request-Headers
                - Access-Control-Request-Method
                - Origin
              QueryString: true
              QueryStringCacheKeys:
                - d
            LambdaFunctionAssociations:
              - EventType: viewer-request
                LambdaFunctionARN: ForwardImageRequestLambdaFunction
              - EventType: origin-response
                LambdaFunctionARN: ResizeImageLambdaFunction
            MinTTL: 100
            PathPattern: '*.png'
            TargetOriginId:
              Ref: S3BucketMovies
            ViewerProtocolPolicy: redirect-to-https
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            Cookies:
              Forward: none
            Headers:
              - Access-Control-Request-Headers
              - Access-Control-Request-Method
              - Origin
            QueryString: false
          LambdaFunctionAssociations:
            - EventType: viewer-request
              LambdaFunctionARN: AuthorizeUserLambdaFunction
          TargetOriginId:
            Ref: S3BucketMovies
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        Origins:
          - DomainName:
              Fn::Join:
                - ''
                - - Ref: S3BucketMovies
                  - .s3.${self:provider.region}.amazonaws.com
            Id:
              Ref: S3BucketMovies
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ''
                  - - origin-access-identity/cloudfront/
                    - Ref: S3BucketMoviesOriginAccessIdentity
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
