Resources:
  S3BucketMovies:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            MaxAge: 3600

  S3BucketMoviesOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment:
          Ref: S3BucketMovies

  S3BucketMoviesPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3BucketMovies
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt:
                  [S3BucketMoviesOriginAccessIdentity, S3CanonicalUserId]
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: S3BucketMovies
                  - /*
          - Action:
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt: [ResizeImageIamRoleEdgeLambdaExecution, Arn]
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: S3BucketMovies
                  - /*
